server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.format_sql: true


  security:
    application:
      name: springboot-keycloak
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9080/auth/realms/agenda
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: internal
      principal-attribute: preferred_username

logging:
  level:
    org.springframework.security: DEBUG

###
# CORS Configurations
#  Use these properties to control which origins can access the external AppBuilder-facing API and the BFF-style API for the Hub MFEs
##
ALLOWED_APPBUILDER_ORIGIN: "*"
ALLOWED_API_ORIGIN:
