name: PR workflow
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  sonarqube:
    runs-on: ubuntu-latest
    container:
      image: entando/ent-cli-github:v7.2.0
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'
    - name: SonarQube Scan
      run: |
        versionSuffix=$(echo "${{ github.event.pull_request.title }}" | awk '{print $1}')
        bash .github/functions/utils.sh setBundleVersion -$versionSuffix
        bash .github/functions/utils.sh setComponentVersions -$versionSuffix
        ent bundle build --all --stdout --fail-fast
        cd microservices/springboot-agenda && mvn sonar:sonar --no-transfer-progress && cd ../..
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
  build:
    runs-on: ubuntu-latest
    container:
      image: entando/ent-cli-github:v7.2.0
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Check PR name
        uses: Slashgear/action-check-pr-title@v4.3.0
        with:
          regexp: "(^ENG-[0-9]{3,5} .*$|^ENGPM-[0-9]{3,5} .*$)"
          helpMessage: "Example: 'ENG-123 A change' or 'ENGPM-123 A change'"
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: registry.hub.docker.com
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Pack the application bundle
        id: pack
        env:
          DOCKER_ORG: entando
        run: |
          versionSuffix=$(echo "${{ github.event.pull_request.title }}" | awk '{print $1}')
          bash .github/functions/utils.sh setBundleVersion -$versionSuffix
          bash .github/functions/utils.sh setComponentVersions -$versionSuffix
          ent --debug bundle pack --org $DOCKER_ORG --stdout --fail-fast
          ent --debug bundle publish
          version=$(bash ../.github/functions/utils.sh getBundleImage)
          echo "VERSION=$version" >> $GITHUB_OUTPUT
      - name: Publish artifact version
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Requested publication of version: `${{ steps.pack.outputs.VERSION }}`
